@baseUrl = http://localhost:3000

### Create Order (populate the database)
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "price": 100.0,
  "tax": 10.0
}

### Create another Order
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "price": 50.0,
  "tax": 5.0
}

### List Orders (validate the challenge)
GET {{baseUrl}}/orders
Accept: application/json

### Liveness
GET {{baseUrl}}/healthz

### Readiness
GET {{baseUrl}}/readyz

### GraphQL - List Orders
POST http://localhost:3001/query
Content-Type: application/json

{
  "query": "{ listOrders { ID Price Tax FinalPrice CreatedAt } }"
}

### GraphQL - Create Order
POST http://localhost:3001/query
Content-Type: application/json

{
  "query": "mutation { createOrder(input: { Price: 200, Tax: 20 }) { ID Price FinalPrice CreatedAt } }"
}
