// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Order struct {
	ID         int       `json:"ID"`
	Price      float64   `json:"Price"`
	Tax        float64   `json:"Tax"`
	FinalPrice float64   `json:"FinalPrice"`
	CreatedAt  time.Time `json:"CreatedAt"`
}

type OrderInput struct {
	Price float64 `json:"Price"`
	Tax   float64 `json:"Tax"`
}

type Query struct {
}
