package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/DSanches92/fullcycle-clean-architecture/internal/infra/graph/generated"
	"github.com/DSanches92/fullcycle-clean-architecture/internal/infra/graph/model"
	"github.com/DSanches92/fullcycle-clean-architecture/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.OrderInput) (*model.Order, error) {
	dto := usecase.OrderInputDTO{
		Price: input.Price,
		Tax:   input.Tax,
	}

	output, err := r.CreateOrderUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}

	return &model.Order{
		ID:         int(output.ID),
		Price:      output.Price,
		Tax:        output.Tax,
		FinalPrice: output.FinalPrice,
		CreatedAt:  orderCreatedAt(output.CreatedAt),
	}, nil
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*model.Order, error) {
	orders, err := r.ListOrdersUseCase.Execute()
	if err != nil {
		return nil, err
	}

	var list []*model.Order
	for _, order := range orders {
		list = append(list, &model.Order{
			ID:         int(order.ID),
			Price:      order.Price,
			Tax:        order.Tax,
			FinalPrice: order.FinalPrice,
			CreatedAt:  orderCreatedAt(order.CreatedAt),
		})
	}

	return list, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
